Resolves issue added filter query support
LeeU1911/jsonbox-java pull request #4
Opened 2019-10-23 16:16 UTC by RushikeshSawant

2019-12-08 06:15 UTC, LeeU1911 reviewed
Thanks for your contribution. Looks good. Just a small comment or two then I can merge.

2019-12-08 06:15 UTC, LeeU1911 commented on src/main/java/org/leeu1911/JsonBoxObject.java
> +            return GSON.fromJson(response.getResponseBody(), type);
Please use `parseHttpResponse` method for this.

2019-12-08 06:15 UTC, LeeU1911 commented on src/test/java/org/leeu1911/JsonBoxTest.groovy
> +        JsonBox.boxId = UUID.randomUUID().toString().replaceAll("-","_")
I wanted to fixed the `boxId` to not pollute jsonbox with test data for every time test suite runs. Did you have a problem with your tests so you had to change this? If not, let's revert this change.

2019-12-08 06:16 UTC, LeeU1911 requested changes
Please update your PR with points mentioned.

2019-12-23 14:26 UTC, RushikeshSawant commented
@LeeU1911 updated my PR to address your comments

2021-03-24 15:38 UTC, closed without merging